### ISSUE TITLE
rasterize_triangles_cpp not found even after step 6.

### ISSUE THREAD

**Issue by mrlatnek** [xinwen-cs/AudioDVP#21]
I am trying to execute this part of the code after executing all the prior code and all steps including step 6 - 

python train.py \
    --data_dir $video_dir \
    --num_epoch 20 \
    --serial_batches False \
    --display_freq 400 \
    --print_freq 400 \
    --batch_size 5
I encounter this error- 
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from models import resnet_model
  File "/home/ubuntu/AudioDVP-master/models/resnet_model.py", line 6, in <module>
    from . import networks
  File "/home/ubuntu/AudioDVP-master/models/networks.py", line 9, in <module>
    from renderer.face_model import FaceModel
  File "/home/ubuntu/AudioDVP-master/renderer/face_model.py", line 7, in <module>
    from .renderer import Renderer
  File "/home/ubuntu/AudioDVP-master/renderer/renderer.py", line 6, in <module>
    from .rasterizer import Rasterizer
  File "/home/ubuntu/AudioDVP-master/renderer/rasterizer.py", line 8, in <module>
    from .kernels import rasterize_triangles_cpp
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

Pytorch version - 1.4, cudatoolkit - 10.0

**Comment by piwawa** [comment]
How do you solve it?? I am meeting this problem.
