### ISSUE TITLE
RuntimeError: triangles.is_contiguous() INTERNAL ASSERT FAILED   ,can u give some ad

### ISSUE THREAD

**Issue by anthonyyuan** [xinwen-cs/AudioDVP#9]
when I run:
# # # 3D face reconstruction
python train.py \
     --data_dir $video_dir \
     --num_epoch 20 \
     --serial_batches False \
     --display_freq 400 \
     --print_freq 400 \
     --batch_size 5

**Comment by anthonyyuan** [comment]
./scripts/demo.sh
++ video_dir=data/video
++ audio_dir=data/test_audio
++ start_time=00:00:00
++ end_time=240
++ python train.py --data_dir data/video --num_epoch 20 --serial_batches False --display_freq 400 --print_freq 400 --batch_size 5
dataset [SingleDataset] was created
Traceback (most recent call last):
  File "train.py", line 38, in <module>
    model.optimize_parameters()   # calculate loss functions, get gradients, update network weights
  File "/home/anthony/Downloads/AudioDVP-master/models/resnet_model.py", line 69, in optimize_parameters
    self.forward()
  File "/home/anthony/Downloads/AudioDVP-master/models/resnet_model.py", line 48, in forward
    self.alpha, self.delta, self.beta, self.gamma, self.rotation, self.translation, self.render, self.mask, self.landmark = self.net(self.input)
  File "/home/anthony/Downloads/ENTER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anthony/Downloads/AudioDVP-master/models/networks.py", line 174, in forward
    render, mask, screen_vertices = self.face_model(self.alpha, delta, self.beta, rotation, translation, gamma)
  File "/home/anthony/Downloads/ENTER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anthony/Downloads/AudioDVP-master/renderer/face_model.py", line 100, in forward
    render_image, alpha_mask = self.renderer(clip_vertices, self.triangles, norm, tex, gamma)
  File "/home/anthony/Downloads/ENTER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anthony/Downloads/AudioDVP-master/renderer/renderer.py", line 22, in forward
    render_image, alpha_mask = self.rasterizer(clip_vertices, diffuse_colors_sh, triangles)
  File "/home/anthony/Downloads/ENTER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anthony/Downloads/AudioDVP-master/renderer/rasterizer.py", line 53, in forward
    px_triangle_ids, px_barycentric_coords, _ = RasterizeFunction.apply(clip_vertices[b, :, :], triangles, self.image_width, self.image_height)
  File "/home/anthony/Downloads/AudioDVP-master/renderer/rasterizer.py", line 19, in forward
    = rasterize_triangles_cpp.forward(vertices, triangles, image_width, image_height,px_triangle_ids, px_barycentric_coords, z_buffer)
RuntimeError: triangles.is_contiguous() INTERNAL ASSERT FAILED at "/home/anthony/Downloads/AudioDVP-master/renderer/kernels/rasterize_triangles.cpp":47, please report a bug to PyTorch. triangles must be contiguous

**Comment by qpoisson** [comment]
@anthonyyuan   how did you solve the issue ? thx

**Comment by ghost** [comment]
@anthonyyuan how did you solve the issue ? 
I meet it too.
@xinwen-cs
